import type {
  Product,
  Category,
  Brand,
  User,
  Address,
  Order,
  RFQ,
  Quote,
  TaxInvoice,
  Notification,
  Conversation,
  ChatMessage,
} from '../types';

export const INITIAL_USER: User = {
  id: 'usr_buyer_101',
  name: 'Rajesh Sharma',
  email: 'rajesh@infraapex.com',
  phone: '+91 98490 28140',
  companyName: 'Apex Infra & Construction Ltd.',
  gstin: '36AAACA1234F1Z8',
  pan: 'AAACA1234F',
  businessType: 'Private Limited',
  industry: 'Infrastructure & Commercial Construction',
  isGstVerified: true,
  isApprovedBuyer: true,
  creditLimit: 2500000,
  creditAvailable: 1850000,
  creditDays: 30,
};

export const INITIAL_ADDRESSES: Address[] = [
  {
    id: 'addr_1',
    contactName: 'Rajesh Sharma (Project Head)',
    mobile: '+91 98490 28140',
    companyName: 'Apex Infra & Construction Ltd. (Site #4)',
    gstin: '36AAACA1234F1Z8',
    addressLine1: 'Plot 48, Financial District, Nanakramguda',
    addressLine2: 'Adjacent to Wave Rock IT Park',
    landmark: 'Opposite Oakridge School',
    city: 'Hyderabad',
    state: 'Telangana',
    pincode: '500032',
    addressType: 'Site / Project',
    isDefaultDelivery: true,
    isDefaultBilling: false,
  },
  {
    id: 'addr_2',
    contactName: 'Suresh Verma (Procurement)',
    mobile: '+91 98490 28141',
    companyName: 'Apex Infra Central Warehouse',
    gstin: '36AAACA1234F1Z8',
    addressLine1: 'Shed 12, Industrial Development Area, Patancheru',
    addressLine2: 'Phase II, Near ORR Exit 3',
    landmark: 'Behind Bharat Petroleum Pump',
    city: 'Hyderabad',
    state: 'Telangana',
    pincode: '502319',
    addressType: 'Warehouse / Factory',
    isDefaultDelivery: false,
    isDefaultBilling: false,
  },
  {
    id: 'addr_3',
    contactName: 'Accounts Department',
    mobile: '+91 98490 28142',
    companyName: 'Apex Infra & Construction Ltd. (Corporate HQ)',
    gstin: '36AAACA1234F1Z8',
    addressLine1: 'Suite 804, Manjeera Trinity Corporate, KPHB Colony',
    addressLine2: 'JNTU-Hitech City Road, Kukatpally',
    landmark: 'Next to Forum Sujana Mall',
    city: 'Hyderabad',
    state: 'Telangana',
    pincode: '500072',
    addressType: 'Office / Commercial',
    isDefaultDelivery: false,
    isDefaultBilling: true,
  },
];

export const CATEGORIES: Category[] = [
  {
    id: 'cat_steel',
    name: 'Steel & Structural Metals',
    slug: 'steel-structural-metals',
    iconName: 'Boxes',
    image: 'https://images.unsplash.com/photo-1587293852726-70cdb56c2866?auto=format&fit=crop&w=600&q=80',
    description: 'Primary & Secondary TMT Bars, Structural Beams, Channels, Angles, GI Sheets & Coils.',
    subcategories: [
      { id: 'sub_tmt', name: 'TMT Bars (Fe 550D / 500D)', slug: 'tmt-bars', itemCount: 68 },
      { id: 'sub_structural', name: 'Structural Steel (Beams & Channels)', slug: 'structural-steel', itemCount: 44 },
      { id: 'sub_angles', name: 'MS Angles & Flats', slug: 'ms-angles-flats', itemCount: 32 },
      { id: 'sub_gi_sheets', name: 'GI & Color Coated Roofing Sheets', slug: 'roofing-sheets', itemCount: 29 },
      { id: 'sub_binding_wire', name: 'Binding Wire & Stirrups', slug: 'binding-wire', itemCount: 18 },
    ],
  },
  {
    id: 'cat_cement',
    name: 'Cement & Ready Mix',
    slug: 'cement-ready-mix',
    iconName: 'Layers',
    image: 'https://images.unsplash.com/photo-1590069261209-f8e9b8642343?auto=format&fit=crop&w=600&q=80',
    description: 'OPC 53, PPC, PSC Grade Cements, White Cement & Commercial Ready-Mix Concrete.',
    subcategories: [
      { id: 'sub_opc53', name: 'OPC 53 Grade Cement', slug: 'opc-53-cement', itemCount: 24 },
      { id: 'sub_ppc', name: 'PPC Portland Pozzolana Cement', slug: 'ppc-cement', itemCount: 31 },
      { id: 'sub_white_cement', name: 'White Cement & Wall Putty', slug: 'white-cement-putty', itemCount: 19 },
      { id: 'sub_rmc', name: 'Ready-Mix Concrete (M20 to M40)', slug: 'ready-mix-concrete', itemCount: 15 },
    ],
  },
  {
    id: 'cat_electrical',
    name: 'Electrical & Industrial Cables',
    slug: 'electrical-cables',
    iconName: 'Zap',
    image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=600&q=80',
    description: 'HT/LT Armoured Cables, Industrial Wires, Switchgear, Distribution Boards, Motors & Transformers.',
    subcategories: [
      { id: 'sub_armoured_cables', name: 'Armoured Power Cables', slug: 'armoured-cables', itemCount: 85 },
      { id: 'sub_house_wires', name: 'FR-LSH Building Wires', slug: 'building-wires', itemCount: 62 },
      { id: 'sub_switchgear', name: 'MCBs, MCCBs & DBs', slug: 'mcb-mccb-switchgear', itemCount: 94 },
      { id: 'sub_industrial_lighting', name: 'High Bay & Flood LED Lights', slug: 'industrial-led-lighting', itemCount: 41 },
      { id: 'sub_conduits', name: 'PVC & GI Electrical Conduits', slug: 'electrical-conduits', itemCount: 37 },
    ],
  },
  {
    id: 'cat_pipes',
    name: 'Pipes & Plumbing Systems',
    slug: 'pipes-plumbing',
    iconName: 'Pipette',
    image: 'https://images.unsplash.com/photo-1542013936693-884638332954?auto=format&fit=crop&w=600&q=80',
    description: 'CPVC, UPVC, SWR, HDPE Pipes, Industrial Valves, Flanges and Water Tanks.',
    subcategories: [
      { id: 'sub_cpvc', name: 'CPVC Pipes & Fittings (SDR 11/13.5)', slug: 'cpvc-pipes-fittings', itemCount: 76 },
      { id: 'sub_hdpe', name: 'HDPE Water & Drainage Pipes (PN6/PN10)', slug: 'hdpe-pipes', itemCount: 48 },
      { id: 'sub_valves', name: 'Industrial Butterfly & Gate Valves', slug: 'industrial-valves', itemCount: 53 },
      { id: 'sub_pumps', name: 'Commercial Submersible & Dewatering Pumps', slug: 'commercial-pumps', itemCount: 34 },
    ],
  },
  {
    id: 'cat_tools',
    name: 'Power Tools & Heavy Machinery',
    slug: 'power-tools-machinery',
    iconName: 'Wrench',
    image: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&w=600&q=80',
    description: 'Rotary Hammers, Cut-off Saws, Angle Grinders, Bar Bending Machines, Generators & Vibrators.',
    subcategories: [
      { id: 'sub_rotary_hammers', name: 'Demolition & Rotary Hammer Drills', slug: 'rotary-hammers', itemCount: 42 },
      { id: 'sub_grinders_cutters', name: 'Heavy Duty Grinders & Metal Cutters', slug: 'grinders-cutters', itemCount: 38 },
      { id: 'sub_bar_machines', name: 'Bar Bending & Cutting Machines', slug: 'bar-bending-machines', itemCount: 16 },
      { id: 'sub_concrete_vibrators', name: 'Concrete Vibrators & Mixers', slug: 'concrete-mixers-vibrators', itemCount: 22 },
      { id: 'sub_welding', name: 'MIG/TIG Inverter Welding Machines', slug: 'welding-machines', itemCount: 27 },
    ],
  },
  {
    id: 'cat_safety',
    name: 'Safety & Industrial PPE',
    slug: 'safety-ppe',
    iconName: 'ShieldAlert',
    image: 'https://images.unsplash.com/photo-1578873375969-d71e3c3d526e?auto=format&fit=crop&w=600&q=80',
    description: 'IS-Certified Safety Helmets, Steel Toe Shoes, Full Body Harnesses, Gloves & Eye Protection.',
    subcategories: [
      { id: 'sub_helmets', name: 'Industrial Safety Helmets (IS 2925)', slug: 'safety-helmets', itemCount: 28 },
      { id: 'sub_shoes', name: 'Steel Toe Safety Shoes (S1P/S3)', slug: 'safety-shoes', itemCount: 45 },
      { id: 'sub_fall_protection', name: 'Full Body Harness & Lanyards (IS 3521)', slug: 'fall-protection-harness', itemCount: 24 },
      { id: 'sub_jackets', name: 'High-Visibility Reflective Jackets', slug: 'high-visibility-jackets', itemCount: 19 },
    ],
  },
  {
    id: 'cat_hardware',
    name: 'Hardware, Fasteners & Scaffolding',
    slug: 'hardware-fasteners',
    iconName: 'Hammer',
    image: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=600&q=80',
    description: 'High Tensile Anchor Fasteners, MS Clamps, Couplers, Scaffolding Jacks and Formwork Accessories.',
    subcategories: [
      { id: 'sub_fasteners', name: 'High Tensile Bolts & Chemical Anchors', slug: 'high-tensile-anchors', itemCount: 63 },
      { id: 'sub_scaffolding', name: 'Scaffolding Couplers & Base Jacks', slug: 'scaffolding-accessories', itemCount: 39 },
      { id: 'sub_plywood', name: 'Shuttering Plywood (Film Faced)', slug: 'shuttering-plywood', itemCount: 25 },
    ],
  },
  {
    id: 'cat_chemicals',
    name: 'Construction Chemicals & Paints',
    slug: 'chemicals-paints',
    iconName: 'Paintbrush',
    image: 'https://images.unsplash.com/photo-1562259949-e8e7689d7828?auto=format&fit=crop&w=600&q=80',
    description: 'Integral Waterproofing, Admixtures, Epoxy Grouts, Anti-Corrosive Primers & Industrial Coatings.',
    subcategories: [
      { id: 'sub_waterproofing', name: 'Integral & Membrane Waterproofing', slug: 'waterproofing-compounds', itemCount: 36 },
      { id: 'sub_admixtures', name: 'Plasticizers & Curing Compounds', slug: 'concrete-admixtures', itemCount: 28 },
      { id: 'sub_coatings', name: 'Industrial Anti-Corrosive Epoxy & PU', slug: 'industrial-coatings', itemCount: 34 },
    ],
  },
];

export const BRANDS: Brand[] = [
  { id: 'b_tata', name: 'TATA Tiscon', logo: 'https://placehold.co/160x80/0f172a/ffffff?text=TATA+TISCON', category: 'Steel', productCount: 48 },
  { id: 'b_ultratech', name: 'UltraTech Cement', logo: 'https://placehold.co/160x80/0f172a/ffffff?text=ULTRATECH', category: 'Cement', productCount: 36 },
  { id: 'b_jsw', name: 'JSW Neosteel', logo: 'https://placehold.co/160x80/0f172a/ffffff?text=JSW+STEEL', category: 'Steel', productCount: 42 },
  { id: 'b_polycab', name: 'Polycab', logo: 'https://placehold.co/160x80/0f172a/ffffff?text=POLYCAB', category: 'Electrical', productCount: 78 },
  { id: 'b_bosch', name: 'Bosch Power Tools', logo: 'https://placehold.co/160x80/0f172a/ffffff?text=BOSCH', category: 'Tools', productCount: 54 },
  { id: 'b_astral', name: 'Astral Pipes', logo: 'https://placehold.co/160x80/0f172a/ffffff?text=ASTRAL+PIPES', category: 'Pipes', productCount: 65 },
  { id: 'b_asianpaints', name: 'Asian Paints PPG', logo: 'https://placehold.co/160x80/0f172a/ffffff?text=ASIAN+PAINTS', category: 'Chemicals', productCount: 49 },
  { id: 'b_schneider', name: 'Schneider Electric', logo: 'https://placehold.co/160x80/0f172a/ffffff?text=SCHNEIDER', category: 'Electrical', productCount: 61 },
  { id: 'b_3m', name: '3M Safety', logo: 'https://placehold.co/160x80/0f172a/ffffff?text=3M+SAFETY', category: 'Safety', productCount: 38 },
  { id: 'b_makita', name: 'Makita', logo: 'https://placehold.co/160x80/0f172a/ffffff?text=MAKITA', category: 'Tools', productCount: 32 },
  { id: 'b_finolex', name: 'Finolex Cables', logo: 'https://placehold.co/160x80/0f172a/ffffff?text=FINOLEX', category: 'Electrical', productCount: 44 },
  { id: 'b_supreme', name: 'Supreme Industries', logo: 'https://placehold.co/160x80/0f172a/ffffff?text=SUPREME', category: 'Pipes', productCount: 52 },
];

export const PRODUCTS: Product[] = [
  {
    id: 'prod_tata_550d_12mm',
    slug: 'tata-tiscon-550d-12mm-tmt-bar',
    title: 'TATA Tiscon 550D High-Ductility TMT Rebar (12mm)',
    brand: 'TATA Tiscon',
    category: 'Steel & Structural Metals',
    categoryId: 'cat_steel',
    subcategory: 'TMT Bars (Fe 550D / 500D)',
    subcategoryId: 'sub_tmt',
    description: 'TATA Tiscon 550D is India’s foremost earthquake-resistant green steel rebar. Features high elongation, superior bendability, enhanced rib pattern for 100% concrete bond, and primary steel billet purity. Ideal for heavy load RCC columns, flyovers, commercial basements, and high-rise towers.',
    images: [
      'https://images.unsplash.com/photo-1587293852726-70cdb56c2866?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1504917599217-d4dc5ebe6122?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1535813547-99c456a41d4a?auto=format&fit=crop&w=800&q=80',
    ],
    price: 61500,
    mrp: 64800,
    unit: 'Ton',
    moq: 1,
    gstRate: 18,
    hsnCode: '72142090',
    bulkPricing: [
      { minQty: 1, maxQty: 4, pricePerUnit: 61500, discountPercent: 0 },
      { minQty: 5, maxQty: 9, pricePerUnit: 60800, discountPercent: 1.1 },
      { minQty: 10, maxQty: 24, pricePerUnit: 59900, discountPercent: 2.6 },
      { minQty: 25, maxQty: null, pricePerUnit: 58800, discountPercent: 4.4 },
    ],
    stock: 120,
    rating: 4.8,
    ratingCount: 148,
    seller: {
      id: 'sel_sri_sai',
      name: 'Sri Sai Steel Traders & Distributors',
      isVerified: true,
      rating: 4.8,
      city: 'Hyderabad',
      state: 'Telangana',
      successfulOrders: 1420,
      gstinMasked: '36*****4Z1',
      phoneMasked: '+91 98*** **410',
    },
    specifications: [
      { name: 'Brand', value: 'TATA Tiscon' },
      { name: 'Steel Grade', value: 'Fe 550D High Ductility' },
      { name: 'Nominal Diameter', value: '12 mm' },
      { name: 'Standard Length', value: '12 Meters / Piece' },
      { name: 'Yield Strength', value: '≥ 550 N/mm²' },
      { name: 'Elongation', value: '≥ 16% (Earthquake proof)' },
      { name: 'Manufacturing Process', value: 'Primary Billet Thermo-Mechanical Treatment' },
      { name: 'Carbon Equivalent', value: '≤ 0.42%' },
      { name: 'Standard Certification', value: 'IS 1786:2008 Certified' },
      { name: 'Country of Origin', value: 'India' },
    ],
    isFeatured: true,
    isBulkDeal: true,
    tags: ['TMT Steel', 'Earthquake Resistant', 'Fe 550D', 'TATA', 'Primary Rebar'],
    industries: ['Construction', 'Infrastructure', 'Fabrication'],
    deliveryDays: 3,
    deliveryCharge: 2500,
    freeDeliveryAbove: 200000,
  },
  {
    id: 'prod_ultratech_ppc_50kg',
    slug: 'ultratech-ppc-cement-50kg-bag',
    title: 'UltraTech PPC Weather Plus Cement (50 Kg Bag)',
    brand: 'UltraTech Cement',
    category: 'Cement & Ready Mix',
    categoryId: 'cat_cement',
    subcategory: 'PPC Portland Pozzolana Cement',
    subcategoryId: 'sub_ppc',
    description: 'UltraTech Weather Plus Portland Pozzolana Cement is engineered with water-repellent micro-particles to protect structures from dampness, efflorescence, and corrosion. Perfect for brickwork, external plastering, slab casting, and foundation footing.',
    images: [
      'https://images.unsplash.com/photo-1590069261209-f8e9b8642343?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&w=800&q=80',
    ],
    price: 409,
    mrp: 445,
    unit: 'Bag',
    moq: 50,
    gstRate: 28,
    hsnCode: '25232910',
    bulkPricing: [
      { minQty: 50, maxQty: 199, pricePerUnit: 409, discountPercent: 0 },
      { minQty: 200, maxQty: 499, pricePerUnit: 398, discountPercent: 2.7 },
      { minQty: 500, maxQty: 999, pricePerUnit: 389, discountPercent: 4.8 },
      { minQty: 1000, maxQty: null, pricePerUnit: 378, discountPercent: 7.5 },
    ],
    stock: 4500,
    rating: 4.7,
    ratingCount: 312,
    seller: {
      id: 'sel_deccan_build',
      name: 'Deccan Building Materials Consortium',
      isVerified: true,
      rating: 4.7,
      city: 'Hyderabad',
      state: 'Telangana',
      successfulOrders: 2890,
      gstinMasked: '36*****9Z3',
      phoneMasked: '+91 94*** **820',
    },
    specifications: [
      { name: 'Brand', value: 'UltraTech Cement' },
      { name: 'Cement Type', value: 'Portland Pozzolana Cement (PPC)' },
      { name: 'Packaging Unit', value: '50 Kg HDPE Tamper-Proof Bag' },
      { name: 'Compressive Strength (28 Days)', value: '≥ 53 MPa' },
      { name: 'Initial Setting Time', value: '≥ 30 Minutes' },
      { name: 'Final Setting Time', value: '≤ 600 Minutes' },
      { name: 'Special Feature', value: 'Water-Repellent Weather Proofing' },
      { name: 'Standard Certification', value: 'IS 1489 (Part 1)' },
      { name: 'Country of Origin', value: 'India' },
    ],
    isFeatured: true,
    isBulkDeal: true,
    tags: ['UltraTech', 'PPC Cement', 'Weather Plus', '50kg Bag', 'Waterproofing'],
    industries: ['Construction', 'Infrastructure', 'Plumbing'],
    deliveryDays: 2,
    deliveryCharge: 1800,
    freeDeliveryAbove: 100000,
  },
  {
    id: 'prod_jsw_neosteel_16mm',
    slug: 'jsw-neosteel-550d-16mm-tmt-bar',
    title: 'JSW Neosteel Fe 550D TMT Bar (16mm Heavy Rebar)',
    brand: 'JSW Neosteel',
    category: 'Steel & Structural Metals',
    categoryId: 'cat_steel',
    subcategory: 'TMT Bars (Fe 550D / 500D)',
    subcategoryId: 'sub_tmt',
    description: 'JSW Neosteel Fe 550D is manufactured using virgin iron ore and state-of-the-art Morgan rolling mill technology. Superior bendability and uniform parallel rib structure for heavy civil infrastructure, bridges, and industrial warehouse floors.',
    images: [
      'https://images.unsplash.com/photo-1504917599217-d4dc5ebe6122?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1587293852726-70cdb56c2866?auto=format&fit=crop&w=800&q=80',
    ],
    price: 60800,
    mrp: 63500,
    unit: 'Ton',
    moq: 1,
    gstRate: 18,
    hsnCode: '72142090',
    bulkPricing: [
      { minQty: 1, maxQty: 4, pricePerUnit: 60800, discountPercent: 0 },
      { minQty: 5, maxQty: 14, pricePerUnit: 59900, discountPercent: 1.5 },
      { minQty: 15, maxQty: null, pricePerUnit: 58500, discountPercent: 3.8 },
    ],
    stock: 95,
    rating: 4.6,
    ratingCount: 92,
    seller: {
      id: 'sel_sri_sai',
      name: 'Sri Sai Steel Traders & Distributors',
      isVerified: true,
      rating: 4.8,
      city: 'Hyderabad',
      state: 'Telangana',
      successfulOrders: 1420,
      gstinMasked: '36*****4Z1',
    },
    specifications: [
      { name: 'Brand', value: 'JSW Neosteel' },
      { name: 'Steel Grade', value: 'Fe 550D' },
      { name: 'Nominal Diameter', value: '16 mm' },
      { name: 'Standard Length', value: '12 Meters' },
      { name: 'Standard Certification', value: 'IS 1786:2008' },
      { name: 'Country of Origin', value: 'India' },
    ],
    isFeatured: false,
    isBulkDeal: true,
    tags: ['JSW', '16mm Rebar', 'Fe 550D', 'TMT Bar'],
    industries: ['Construction', 'Infrastructure', 'Fabrication'],
    deliveryDays: 3,
    deliveryCharge: 2500,
  },
  {
    id: 'prod_polycab_4core_16sqmm',
    slug: 'polycab-4core-16sqmm-armoured-cable-100m',
    title: 'Polycab 4 Core 16 Sq.mm Aluminium XLPE Armoured Power Cable (100 Meter Drum)',
    brand: 'Polycab',
    category: 'Electrical & Industrial Cables',
    categoryId: 'cat_electrical',
    subcategory: 'Armoured Power Cables',
    subcategoryId: 'sub_armoured_cables',
    description: 'Polycab 1.1kV XLPE insulated, PVC inner sheathed, Galvanized Steel round wire / strip armoured, heavy duty industrial power cable. Perfect for underground mains feeder, industrial panels, generator incoming supplies, and site substation installations.',
    images: [
      'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80',
    ],
    price: 34500,
    mrp: 39200,
    unit: 'Drum',
    moq: 1,
    gstRate: 18,
    hsnCode: '85444999',
    bulkPricing: [
      { minQty: 1, maxQty: 2, pricePerUnit: 34500, discountPercent: 0 },
      { minQty: 3, maxQty: 5, pricePerUnit: 33200, discountPercent: 3.7 },
      { minQty: 6, maxQty: null, pricePerUnit: 31800, discountPercent: 7.8 },
    ],
    stock: 45,
    rating: 4.9,
    ratingCount: 88,
    seller: {
      id: 'sel_bharat_electric',
      name: 'Bharat Industrial Electricals Ltd.',
      isVerified: true,
      rating: 4.9,
      city: 'Secunderabad',
      state: 'Telangana',
      successfulOrders: 3140,
      gstinMasked: '36*****7K9',
    },
    specifications: [
      { name: 'Brand', value: 'Polycab' },
      { name: 'Conductor Material', value: 'High Conductivity EC Grade Aluminium' },
      { name: 'Conductor Size', value: '16 Sq.mm (4 Cores)' },
      { name: 'Insulation', value: 'XLPE (Cross-linked Polyethylene)' },
      { name: 'Voltage Grade', value: '1100 Volts (1.1 kV)' },
      { name: 'Armouring', value: 'Galvanized Steel Strip / Wire Armoured (A2XWY)' },
      { name: 'Standard Length', value: '100 Meters / Drum' },
      { name: 'Standard Certification', value: 'IS 7098 (Part 1)' },
    ],
    isFeatured: true,
    isBulkDeal: true,
    tags: ['Polycab', 'Armoured Cable', '16 sqmm', 'Industrial Power Cable', '4 Core'],
    industries: ['Electrical Contractors', 'Manufacturing', 'Infrastructure', 'Solar'],
    deliveryDays: 2,
    deliveryCharge: 1200,
  },
  {
    id: 'prod_bosch_gsh_11e',
    slug: 'bosch-gsh-11e-professional-demolition-hammer',
    title: 'Bosch GSH 11 E Professional 1500W SDS-Max Heavy Demolition Breaker',
    brand: 'Bosch Power Tools',
    category: 'Power Tools & Heavy Machinery',
    categoryId: 'cat_tools',
    subcategory: 'Demolition & Rotary Hammer Drills',
    subcategoryId: 'sub_rotary_hammers',
    description: 'The specialist heavy-duty breaker for horizontal wall breakthroughs and concrete chipping. Features 16.8 Joules single impact force, constant electronic speed control, and robust metal housing designed for heavy construction continuous shifts.',
    images: [
      'https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',
    ],
    price: 46800,
    mrp: 52900,
    unit: 'Piece',
    moq: 1,
    gstRate: 18,
    hsnCode: '84672100',
    bulkPricing: [
      { minQty: 1, maxQty: 2, pricePerUnit: 46800, discountPercent: 0 },
      { minQty: 3, maxQty: 5, pricePerUnit: 44900, discountPercent: 4.0 },
      { minQty: 6, maxQty: null, pricePerUnit: 43200, discountPercent: 7.7 },
    ],
    stock: 28,
    rating: 4.8,
    ratingCount: 76,
    seller: {
      id: 'sel_machinery_hub',
      name: 'Allied Machinery & Power Tools Hub',
      isVerified: true,
      rating: 4.8,
      city: 'Hyderabad',
      state: 'Telangana',
      successfulOrders: 980,
      gstinMasked: '36*****2M4',
    },
    specifications: [
      { name: 'Brand', value: 'Bosch Professional' },
      { name: 'Model', value: 'GSH 11 E' },
      { name: 'Rated Power Input', value: '1500 Watts' },
      { name: 'Impact Energy', value: '16.8 Joules (EPTA)' },
      { name: 'Impact Rate at Rated Speed', value: '900 – 1890 bpm' },
      { name: 'Tool Holder', value: 'SDS-Max Chuck' },
      { name: 'Weight without Cable', value: '10.1 Kg' },
      { name: 'Warranty', value: '1 Year Bosch India Manufacturer Warranty' },
    ],
    isFeatured: true,
    isBulkDeal: false,
    tags: ['Bosch', 'Demolition Hammer', 'SDS Max', 'Concrete Breaker', 'Power Tools'],
    industries: ['Construction', 'Infrastructure', 'Interior & Fit-Out'],
    deliveryDays: 2,
    deliveryCharge: 0,
    freeDeliveryAbove: 10000,
  },
  {
    id: 'prod_astral_cpvc_pro_1inch',
    slug: 'astral-cpvc-pro-sdr11-1inch-pipe-3m',
    title: 'Astral CPVC PRO SDR 11 Hot & Cold Water Pipe 1 Inch (3 Meter Length - Bundle of 10)',
    brand: 'Astral Pipes',
    category: 'Pipes & Plumbing Systems',
    categoryId: 'cat_pipes',
    subcategory: 'CPVC Pipes & Fittings (SDR 11/13.5)',
    subcategoryId: 'sub_cpvc',
    description: 'Astral CPVC PRO is NSF-61 certified chlorinated polyvinyl chloride piping system engineered for pressurized hot and cold water distribution up to 93°C. Non-corrosive, bacteriologically neutral, with zero scale buildup.',
    images: [
      'https://images.unsplash.com/photo-1542013936693-884638332954?auto=format&fit=crop&w=800&q=80',
    ],
    price: 4950,
    mrp: 5600,
    unit: 'Bundle',
    moq: 2,
    gstRate: 18,
    hsnCode: '39172300',
    bulkPricing: [
      { minQty: 2, maxQty: 9, pricePerUnit: 4950, discountPercent: 0 },
      { minQty: 10, maxQty: 29, pricePerUnit: 4720, discountPercent: 4.6 },
      { minQty: 30, maxQty: null, pricePerUnit: 4490, discountPercent: 9.3 },
    ],
    stock: 180,
    rating: 4.7,
    ratingCount: 105,
    seller: {
      id: 'sel_deccan_build',
      name: 'Deccan Building Materials Consortium',
      isVerified: true,
      rating: 4.7,
      city: 'Hyderabad',
      state: 'Telangana',
      successfulOrders: 2890,
      gstinMasked: '36*****9Z3',
    },
    specifications: [
      { name: 'Brand', value: 'Astral Pipes' },
      { name: 'Pipe Type', value: 'CPVC PRO SDR 11 (Class 1)' },
      { name: 'Outer Diameter', value: '1 Inch (32mm approx)' },
      { name: 'Standard Length', value: '3 Meters / Piece' },
      { name: 'Packaging', value: 'Bundle of 10 Pipes (30 Meters Total)' },
      { name: 'Pressure Rating', value: '28.1 kg/cm² at 23°C' },
      { name: 'Standard Certification', value: 'IS 15778 / ASTM D2846 / NSF-61' },
    ],
    isFeatured: false,
    isBulkDeal: true,
    tags: ['Astral', 'CPVC Pipe', 'SDR 11', 'Hot Water Plumbing', 'Plumbing Bundle'],
    industries: ['Plumbing', 'Construction', 'Interior & Fit-Out'],
    deliveryDays: 2,
    deliveryCharge: 600,
  },
  {
    id: 'prod_karam_helmet_is2925',
    slug: 'karam-shelmet-sheltek-is2925-pack50',
    title: 'Karam Sheltek Industrial Safety Helmet with Ratchet Nape (Pack of 50)',
    brand: '3M Safety',
    category: 'Safety & Industrial PPE',
    categoryId: 'cat_safety',
    subcategory: 'Industrial Safety Helmets (IS 2925)',
    subcategoryId: 'sub_helmets',
    description: 'High-density polyethylene (HDPE) shell safety helmet conforming to IS 2925:1984. Equipped with 6-point textile suspension, quick-dial ratchet adjustment, sweatband, and 4-point chin strap for construction site engineers and labor teams.',
    images: [
      'https://images.unsplash.com/photo-1578873375969-d71e3c3d526e?auto=format&fit=crop&w=800&q=80',
    ],
    price: 11250,
    mrp: 14500,
    unit: 'Pack',
    moq: 1,
    gstRate: 18,
    hsnCode: '65061090',
    bulkPricing: [
      { minQty: 1, maxQty: 3, pricePerUnit: 11250, discountPercent: 0 },
      { minQty: 4, maxQty: 9, pricePerUnit: 10600, discountPercent: 5.7 },
      { minQty: 10, maxQty: null, pricePerUnit: 9800, discountPercent: 12.8 },
    ],
    stock: 65,
    rating: 4.8,
    ratingCount: 162,
    seller: {
      id: 'sel_safe_guard',
      name: 'SafeGuard Industrial PPE Solutions',
      isVerified: true,
      rating: 4.9,
      city: 'Mumbai',
      state: 'Maharashtra',
      successfulOrders: 2100,
      gstinMasked: '27*****3B2',
    },
    specifications: [
      { name: 'Brand', value: 'Karam / SafeGuard' },
      { name: 'Standard Certification', value: 'IS 2925:1984 Certified' },
      { name: 'Shell Material', value: 'Special HDPE Polymer with UV Stabilization' },
      { name: 'Harness Type', value: '6-Point Textile Cradle with Ratchet adjustment' },
      { name: 'Quantity per Pack', value: '50 Helmets' },
      { name: 'Color Assortment', value: 'White (Supervisors) / Yellow (Workers)' },
    ],
    isFeatured: true,
    isBulkDeal: true,
    tags: ['Safety Helmet', 'PPE', 'IS 2925', 'Site Safety', 'Pack of 50'],
    industries: ['Construction', 'Infrastructure', 'Manufacturing', 'Solar'],
    deliveryDays: 3,
    deliveryCharge: 800,
  },
  {
    id: 'prod_drfixit_lw_plus_20l',
    slug: 'dr-fixit-pidiproof-lw-plus-waterproofing-20l',
    title: 'Dr. Fixit Pidiproof LW+ Integral Liquid Waterproofing Compound (20 Litre Drum)',
    brand: 'Asian Paints PPG',
    category: 'Construction Chemicals & Paints',
    categoryId: 'cat_chemicals',
    subcategory: 'Integral & Membrane Waterproofing',
    subcategoryId: 'sub_waterproofing',
    description: 'Dr. Fixit Pidiproof LW+ is specially formulated integral liquid waterproofing compound composed of surface active plasticising agents, polymers & additives. Used as an additive for cement concrete, mortar & plasters to prevent dampness, bleeding, and segregation.',
    images: [
      'https://images.unsplash.com/photo-1562259949-e8e7689d7828?auto=format&fit=crop&w=800&q=80',
    ],
    price: 3150,
    mrp: 3850,
    unit: 'Drum',
    moq: 2,
    gstRate: 18,
    hsnCode: '38244090',
    bulkPricing: [
      { minQty: 2, maxQty: 9, pricePerUnit: 3150, discountPercent: 0 },
      { minQty: 10, maxQty: 24, pricePerUnit: 2980, discountPercent: 5.3 },
      { minQty: 25, maxQty: null, pricePerUnit: 2820, discountPercent: 10.4 },
    ],
    stock: 140,
    rating: 4.9,
    ratingCount: 220,
    seller: {
      id: 'sel_deccan_build',
      name: 'Deccan Building Materials Consortium',
      isVerified: true,
      rating: 4.7,
      city: 'Hyderabad',
      state: 'Telangana',
      successfulOrders: 2890,
      gstinMasked: '36*****9Z3',
    },
    specifications: [
      { name: 'Brand', value: 'Pidilite / Dr. Fixit' },
      { name: 'Dosage', value: '200 ml per 50 Kg bag of cement' },
      { name: 'Packaging', value: '20 Litres HDPE Drum' },
      { name: 'Standard Certification', value: 'IS 2645:2003 / IS 9103:2000' },
      { name: 'Shelf Life', value: '24 Months from DOM' },
    ],
    isFeatured: false,
    isBulkDeal: true,
    tags: ['Waterproofing', 'Dr Fixit', 'Pidiproof', 'Chemicals', '20L Drum'],
    industries: ['Construction', 'Plumbing', 'Interior & Fit-Out'],
    deliveryDays: 2,
    deliveryCharge: 400,
  },
  {
    id: 'prod_schneider_mccb_250a',
    slug: 'schneider-easypact-ezc250f-3p-250a-mccb',
    title: 'Schneider EasyPact EZC250F 3-Pole 250A 18kA Moulded Case Circuit Breaker (MCCB)',
    brand: 'Schneider Electric',
    category: 'Electrical & Industrial Cables',
    categoryId: 'cat_electrical',
    subcategory: 'MCBs, MCCBs & DBs',
    subcategoryId: 'sub_switchgear',
    description: 'Schneider EasyPact EZC250F is a fixed thermal-magnetic 3P 3d circuit breaker designed for electrical distribution protection in low voltage commercial and industrial distribution boards. Certified for breaking capacity of 18kA at 415V AC.',
    images: [
      'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80',
    ],
    price: 9800,
    mrp: 12400,
    unit: 'Piece',
    moq: 1,
    gstRate: 18,
    hsnCode: '85362090',
    bulkPricing: [
      { minQty: 1, maxQty: 3, pricePerUnit: 9800, discountPercent: 0 },
      { minQty: 4, maxQty: 9, pricePerUnit: 9350, discountPercent: 4.5 },
      { minQty: 10, maxQty: null, pricePerUnit: 8900, discountPercent: 9.1 },
    ],
    stock: 35,
    rating: 4.8,
    ratingCount: 51,
    seller: {
      id: 'sel_bharat_electric',
      name: 'Bharat Industrial Electricals Ltd.',
      isVerified: true,
      rating: 4.9,
      city: 'Secunderabad',
      state: 'Telangana',
      successfulOrders: 3140,
      gstinMasked: '36*****7K9',
    },
    specifications: [
      { name: 'Brand', value: 'Schneider Electric' },
      { name: 'Poles', value: '3 Pole (3P)' },
      { name: 'Rated Current (In)', value: '250 Amperes' },
      { name: 'Breaking Capacity (Icu)', value: '18 kA at 415V AC' },
      { name: 'Trip Unit', value: 'Thermal-Magnetic Fixed' },
      { name: 'Standard Certification', value: 'IEC 60947-2 / IS 13947-2' },
    ],
    isFeatured: false,
    isBulkDeal: false,
    tags: ['Schneider', 'MCCB', '250A', 'Switchgear', 'Electrical Panel'],
    industries: ['Electrical Contractors', 'Manufacturing', 'Infrastructure'],
    deliveryDays: 2,
    deliveryCharge: 0,
    freeDeliveryAbove: 5000,
  },
];

export const ORDERS: Order[] = [
  {
    id: 'ord_hm_2608191024',
    orderNumber: 'HM2608191024',
    createdAt: '2026-08-19T10:24:00+05:30',
    expectedDelivery: '2026-08-23T18:00:00+05:30',
    status: 'In Transit',
    paymentStatus: 'Paid',
    paymentMethod: 'netbanking',
    seller: {
      id: 'sel_sri_sai',
      name: 'Sri Sai Steel Traders & Distributors',
      isVerified: true,
      rating: 4.8,
      city: 'Hyderabad',
      state: 'Telangana',
      successfulOrders: 1420,
      gstinMasked: '36*****4Z1',
    },
    items: [
      {
        productId: 'prod_tata_550d_12mm',
        productTitle: 'TATA Tiscon 550D High-Ductility TMT Rebar (12mm)',
        productImage: 'https://images.unsplash.com/photo-1587293852726-70cdb56c2866?auto=format&fit=crop&w=400&q=80',
        brand: 'TATA Tiscon',
        quantity: 5,
        unit: 'Ton',
        unitPrice: 60800,
        gstRate: 18,
        totalPrice: 304000,
        hsnCode: '72142090',
      },
    ],
    deliveryAddress: INITIAL_ADDRESSES[0],
    billingAddress: INITIAL_ADDRESSES[2],
    subtotal: 307500,
    bulkDiscount: 3500,
    taxableAmount: 304000,
    cgst: 27360,
    sgst: 27360,
    igst: 0,
    deliveryCharge: 2500,
    grandTotal: 361220,
    invoiceId: 'inv_hm_2026_8191',
    tracking: {
      partnerName: 'HinchLogistics / Rivigo Heavy Freight',
      trackingNumber: 'TRK-HM-8849201',
      vehicleNumber: 'TS 09 UA 7742 (24-Ft Multi-Axle)',
      consignmentNumber: 'LR-HYD-2026-99120',
      dispatchDate: '2026-08-20T14:30:00+05:30',
      estimatedDelivery: '2026-08-23T18:00:00+05:30',
      status: 'Consignment in transit from Hyderabad Central Steel Yard to Nanakramguda Site',
      milestones: [
        {
          title: 'Order Placed & Payment Verified',
          description: 'Payment of ₹3,61,220 confirmed via HDFC Corporate Netbanking',
          timestamp: '19 Aug 2026, 10:24 AM',
          completed: true,
          current: false,
          location: 'HinchMart Gateway',
        },
        {
          title: 'Seller Confirmed & E-Way Bill Generated',
          description: 'Sri Sai Steel assigned yard lot #B4. E-Way Bill #281099238491 generated.',
          timestamp: '19 Aug 2026, 03:45 PM',
          completed: true,
          current: false,
          location: 'Sanathnagar Steel Yard, Hyderabad',
        },
        {
          title: 'Material Weighment & Loaded onto Trailer',
          description: 'Gross weight 5.04 Tons weighed on electronic weighbridge. Test certificate attached.',
          timestamp: '20 Aug 2026, 11:20 AM',
          completed: true,
          current: false,
          location: 'Weighbridge Bay 2, Sanathnagar',
        },
        {
          title: 'Dispatched / In Transit',
          description: 'Vehicle TS 09 UA 7742 moving towards Outer Ring Road (ORR) Junction.',
          timestamp: '20 Aug 2026, 02:30 PM',
          completed: true,
          current: true,
          location: 'ORR Exit 17, Gachibowli Approach',
        },
        {
          title: 'Out for Site Delivery',
          description: 'Site gate entry clearance pending at Financial District project site.',
          timestamp: 'Expected 23 Aug 2026, 10:00 AM',
          completed: false,
          current: false,
          location: 'Financial District, Hyderabad',
        },
        {
          title: 'Delivered & Material Inspection Verified',
          description: 'Digital delivery signature and MTC document handover to site engineer.',
          timestamp: 'Expected 23 Aug 2026, 05:00 PM',
          completed: false,
          current: false,
          location: 'Plot 48, Nanakramguda Site',
        },
      ],
    },
  },
  {
    id: 'ord_hm_2608140833',
    orderNumber: 'HM2608140833',
    createdAt: '2026-08-14T11:15:00+05:30',
    expectedDelivery: '2026-08-16T17:00:00+05:30',
    status: 'Delivered',
    paymentStatus: 'Paid',
    paymentMethod: 'bank_transfer',
    seller: {
      id: 'sel_deccan_build',
      name: 'Deccan Building Materials Consortium',
      isVerified: true,
      rating: 4.7,
      city: 'Hyderabad',
      state: 'Telangana',
      successfulOrders: 2890,
      gstinMasked: '36*****9Z3',
    },
    items: [
      {
        productId: 'prod_ultratech_ppc_50kg',
        productTitle: 'UltraTech PPC Weather Plus Cement (50 Kg Bag)',
        productImage: 'https://images.unsplash.com/photo-1590069261209-f8e9b8642343?auto=format&fit=crop&w=400&q=80',
        brand: 'UltraTech Cement',
        quantity: 200,
        unit: 'Bag',
        unitPrice: 398,
        gstRate: 28,
        totalPrice: 79600,
        hsnCode: '25232910',
      },
    ],
    deliveryAddress: INITIAL_ADDRESSES[1],
    billingAddress: INITIAL_ADDRESSES[2],
    subtotal: 81800,
    bulkDiscount: 2200,
    taxableAmount: 79600,
    cgst: 11144,
    sgst: 11144,
    igst: 0,
    deliveryCharge: 1800,
    grandTotal: 103688,
    invoiceId: 'inv_hm_2026_8140',
    tracking: {
      partnerName: 'TCI Freight Logistics',
      trackingNumber: 'TCI-HYD-55102',
      vehicleNumber: 'TS 08 UB 4129',
      consignmentNumber: 'CN-8812903',
      dispatchDate: '2026-08-15T09:00:00+05:30',
      estimatedDelivery: '2026-08-16T16:00:00+05:30',
      status: 'Consignment successfully delivered at Patancheru Warehouse',
      milestones: [
        {
          title: 'Order Placed',
          description: 'Order confirmed with 200 Bags of UltraTech Weather Plus',
          timestamp: '14 Aug 2026, 11:15 AM',
          completed: true,
          current: false,
          location: 'HinchMart Portal',
        },
        {
          title: 'Dispatched',
          description: 'Loaded and dispatched from Miyapur godown',
          timestamp: '15 Aug 2026, 10:30 AM',
          completed: true,
          current: false,
          location: 'Miyapur Godown',
        },
        {
          title: 'Delivered',
          description: 'Received by Suresh Verma at Patancheru Warehouse',
          timestamp: '16 Aug 2026, 04:30 PM',
          completed: true,
          current: true,
          location: 'Patancheru Warehouse, Hyderabad',
        },
      ],
    },
  },
];

export const RFQS: RFQ[] = [
  {
    id: 'rfq_2608190042',
    rfqNumber: 'RFQ2608190042',
    productName: 'TATA Tiscon Fe 550D TMT Rebar (16mm & 20mm Mix)',
    category: 'Steel & Structural Metals',
    brandPreference: 'TATA Tiscon / JSW Neosteel / Jindal Panther',
    quantity: 20,
    unit: 'Ton',
    deliveryLocation: 'Financial District, Gachibowli, Hyderabad',
    deliveryPincode: '500032',
    requiredByDate: '2026-08-30',
    targetPrice: 58000,
    specifications: 'Required for commercial basement slab casting. Material test certificates (MTC) required with each consignment. Strict Fe 550D grade with IS 1786 certification.',
    notes: 'Unloading crane facility available on site. Payment terms requested: 50% Advance on order, balance against dispatch weighment slip.',
    createdAt: '2026-08-19T09:15:00+05:30',
    status: 'Quotes Received',
    quotesCount: 3,
  },
  {
    id: 'rfq_2608150019',
    rfqNumber: 'RFQ2608150019',
    productName: 'Armoured LT Aluminium 3.5 Core 70 sq.mm Cable',
    category: 'Electrical & Industrial Cables',
    brandPreference: 'Polycab / Havells / Finolex',
    quantity: 800,
    unit: 'Meter',
    deliveryLocation: 'Patancheru IDA, Hyderabad',
    deliveryPincode: '502319',
    requiredByDate: '2026-08-28',
    targetPrice: 380,
    specifications: '1100V XLPE insulated, round wire armoured, heavy duty industrial grade.',
    createdAt: '2026-08-15T14:20:00+05:30',
    status: 'Open',
    quotesCount: 1,
  },
];

export const QUOTES: Quote[] = [
  {
    id: 'qte_sai_001',
    rfqId: 'rfq_2608190042',
    seller: {
      id: 'sel_sri_sai',
      name: 'Sri Sai Steel Traders & Distributors',
      isVerified: true,
      rating: 4.8,
      city: 'Hyderabad',
      state: 'Telangana',
      successfulOrders: 1420,
      gstinMasked: '36*****4Z1',
      phoneMasked: '+91 98*** **410',
    },
    pricePerUnit: 58000,
    quantity: 20,
    unit: 'Ton',
    subtotal: 1160000,
    gstRate: 18,
    gstAmount: 208800,
    deliveryCharge: 0,
    landedCost: 1368800,
    deliveryDays: 3,
    validUntil: '2026-08-25T23:59:59+05:30',
    paymentTerms: '50% Advance, 50% on Delivery',
    notes: 'Direct primary stockyard dispatches. Mill test certificate included. Free site delivery within Hyderabad ORR limits.',
    isAccepted: false,
    createdAt: '2026-08-19T14:30:00+05:30',
  },
  {
    id: 'qte_abc_002',
    rfqId: 'rfq_2608190042',
    seller: {
      id: 'sel_abc_metals',
      name: 'ABC Metals & Heavy Infrastructure Supplies',
      isVerified: true,
      rating: 4.6,
      city: 'Secunderabad',
      state: 'Telangana',
      successfulOrders: 890,
      gstinMasked: '36*****8P2',
      phoneMasked: '+91 99*** **123',
    },
    pricePerUnit: 58500,
    quantity: 20,
    unit: 'Ton',
    subtotal: 1170000,
    gstRate: 18,
    gstAmount: 210600,
    deliveryCharge: 4000,
    landedCost: 1384600,
    deliveryDays: 2,
    validUntil: '2026-08-24T18:00:00+05:30',
    paymentTerms: '100% Before Dispatch',
    notes: 'Immediate dispatch within 48 hours from Jeedimetla stock depot.',
    isAccepted: false,
    createdAt: '2026-08-19T16:00:00+05:30',
  },
  {
    id: 'qte_deccan_003',
    rfqId: 'rfq_2608190042',
    seller: {
      id: 'sel_deccan_build',
      name: 'Deccan Building Materials Consortium',
      isVerified: true,
      rating: 4.7,
      city: 'Hyderabad',
      state: 'Telangana',
      successfulOrders: 2890,
      gstinMasked: '36*****9Z3',
      phoneMasked: '+91 94*** **820',
    },
    pricePerUnit: 57800,
    quantity: 20,
    unit: 'Ton',
    subtotal: 1156000,
    gstRate: 18,
    gstAmount: 208080,
    deliveryCharge: 5000,
    landedCost: 1369080,
    deliveryDays: 4,
    validUntil: '2026-08-26T12:00:00+05:30',
    paymentTerms: '30 Days Credit',
    notes: 'Credit terms subject to pre-approval. JSW Neosteel virgin billets.',
    isAccepted: false,
    createdAt: '2026-08-20T10:15:00+05:30',
  },
];

export const INVOICES: TaxInvoice[] = [
  {
    id: 'inv_hm_2026_8191',
    invoiceNumber: 'TAX-INV-HM26-08191',
    invoiceDate: '2026-08-20',
    orderNumber: 'HM2608191024',
    orderId: 'ord_hm_2608191024',
    buyer: {
      companyName: 'Apex Infra & Construction Ltd.',
      contactPerson: 'Rajesh Sharma',
      gstin: '36AAACA1234F1Z8',
      pan: 'AAACA1234F',
      address: 'Suite 804, Manjeera Trinity Corporate, KPHB Colony',
      city: 'Hyderabad',
      state: 'Telangana',
      pincode: '500072',
    },
    seller: {
      companyName: 'Sri Sai Steel Traders & Distributors',
      gstin: '36AABCS9912F1Z4',
      pan: 'AABCS9912F',
      address: 'Plot 18, Phase 1, Sanathnagar Industrial Area',
      city: 'Hyderabad',
      state: 'Telangana',
      pincode: '500018',
    },
    hinchmart: {
      platformName: 'HinchMart B2B Marketplace Private Limited',
      gstin: '36AABCH4910M1Z2',
      cin: 'U74999TG2024PTC189201',
      address: 'Level 5, HinchMart Towers, Hitech City, Hyderabad, Telangana - 500081',
    },
    items: [
      {
        description: 'TATA Tiscon 550D High-Ductility TMT Rebar (12mm) - IS 1786:2008 Certified',
        hsnCode: '72142090',
        quantity: 5,
        unit: 'Ton',
        unitPrice: 60800,
        taxableValue: 304000,
        gstRate: 18,
        cgstAmount: 27360,
        sgstAmount: 27360,
        igstAmount: 0,
        totalAmount: 358720,
      },
    ],
    taxableTotal: 304000,
    cgstTotal: 27360,
    sgstTotal: 27360,
    igstTotal: 0,
    freightAmount: 2500,
    grandTotal: 361220,
    paymentStatus: 'PAID (HDFC Corporate Netbanking Ref: HD2608198901)',
    paymentMethod: 'Net Banking',
    eWayBillNo: '281099238491',
  },
];

export const NOTIFICATIONS: Notification[] = [
  {
    id: 'notif_1',
    title: 'Order Dispatched & In Transit',
    message: 'Your order HM2608191024 for 5 Tons TATA Tiscon 550D has been loaded onto trailer TS 09 UA 7742.',
    category: 'delivery',
    createdAt: '2026-08-20T14:35:00+05:30',
    isRead: false,
    link: '/account/orders/ord_hm_2608191024',
  },
  {
    id: 'notif_2',
    title: '3 New Quotations Received',
    message: 'Sri Sai Steel, ABC Metals, and Deccan Building have quoted for RFQ #RFQ2608190042 (20 Tons TMT).',
    category: 'quote',
    createdAt: '2026-08-20T10:20:00+05:30',
    isRead: false,
    link: '/account/rfqs/rfq_2608190042/quotes',
  },
  {
    id: 'notif_3',
    title: 'Payment Successful',
    message: '₹3,61,220 successfully processed for Order #HM2608191024. Tax invoice generated.',
    category: 'payment',
    createdAt: '2026-08-19T10:25:00+05:30',
    isRead: true,
    link: '/account/invoices',
  },
  {
    id: 'notif_4',
    title: 'Order Delivered',
    message: 'Order #HM2608140833 (200 Bags UltraTech Cement) has been delivered to Patancheru Warehouse.',
    category: 'order',
    createdAt: '2026-08-16T16:35:00+05:30',
    isRead: true,
    link: '/account/orders/ord_hm_2608140833',
  },
];

export const CONVERSATIONS: Conversation[] = [
  {
    id: 'conv_1',
    seller: {
      id: 'sel_sri_sai',
      name: 'Sri Sai Steel Traders & Distributors',
      isVerified: true,
      rating: 4.8,
      city: 'Hyderabad',
      state: 'Telangana',
      successfulOrders: 1420,
      gstinMasked: '36*****4Z1',
      phoneMasked: '+91 98*** **410',
    },
    topic: 'RFQ Discussion',
    subject: 'Regarding RFQ #RFQ2608190042 - 20 Tons TMT Steel',
    referenceId: 'RFQ2608190042',
    lastMessage: 'Yes, we can supply test certificates and ensure delivery in 3 days.',
    lastMessageTime: '2026-08-20T11:40:00+05:30',
    unreadCount: 1,
  },
  {
    id: 'conv_2',
    seller: {
      id: 'sel_bharat_electric',
      name: 'Bharat Industrial Electricals Ltd.',
      isVerified: true,
      rating: 4.9,
      city: 'Secunderabad',
      state: 'Telangana',
      successfulOrders: 3140,
      gstinMasked: '36*****7K9',
    },
    topic: 'Product Inquiry',
    subject: 'Polycab 4 Core 16 Sq.mm Armoured Cable Availability',
    referenceId: 'prod_polycab_4core_16sqmm',
    lastMessage: 'We have 45 ready drums in Secunderabad godown for immediate dispatch.',
    lastMessageTime: '2026-08-18T16:20:00+05:30',
    unreadCount: 0,
  },
];

export const MESSAGES: Record<string, ChatMessage[]> = {
  conv_1: [
    {
      id: 'msg_101',
      conversationId: 'conv_1',
      sender: 'buyer',
      senderName: 'Rajesh Sharma (Apex Infra)',
      message: 'Hi Sri Sai Steel, we have an urgent RCC slab casting starting next Monday. Can you guarantee delivery of 20 Tons Fe 550D by Friday afternoon?',
      timestamp: '2026-08-20T11:10:00+05:30',
      status: 'read',
    },
    {
      id: 'msg_102',
      conversationId: 'conv_1',
      sender: 'seller',
      senderName: 'Sri Sai Steel Desk',
      message: 'Hello Mr. Rajesh. Yes, we have primary billet coils ready for straightening in our Sanathnagar yard. We can deliver within 3 days (by Thursday evening).',
      timestamp: '2026-08-20T11:25:00+05:30',
      status: 'read',
    },
    {
      id: 'msg_103',
      conversationId: 'conv_1',
      sender: 'buyer',
      senderName: 'Rajesh Sharma (Apex Infra)',
      message: 'Excellent. Please confirm whether the quoted price of ₹58,000 / Ton is inclusive of freight and whether mill test certificates (MTC) will accompany the truck.',
      timestamp: '2026-08-20T11:32:00+05:30',
      status: 'read',
    },
    {
      id: 'msg_104',
      conversationId: 'conv_1',
      sender: 'seller',
      senderName: 'Sri Sai Steel Desk',
      message: 'Yes, we can supply test certificates and ensure delivery in 3 days. Free site freight is included within Hyderabad ORR. You can accept the quotation on HinchMart to lock in the batch.',
      timestamp: '2026-08-20T11:40:00+05:30',
      status: 'delivered',
    },
  ],
  conv_2: [
    {
      id: 'msg_201',
      conversationId: 'conv_2',
      sender: 'buyer',
      senderName: 'Rajesh Sharma (Apex Infra)',
      message: 'Do you have Polycab 4 Core 16 sq.mm XLPE cables in 500 meter continuous drum lengths?',
      timestamp: '2026-08-18T15:45:00+05:30',
      status: 'read',
    },
    {
      id: 'msg_202',
      conversationId: 'conv_2',
      sender: 'seller',
      senderName: 'Bharat Electricals Desk',
      message: 'We have 45 ready drums in Secunderabad godown for immediate dispatch. Standard 100m drums are ready, and 500m drums can be dispatched in 48 hours.',
      timestamp: '2026-08-18T16:20:00+05:30',
      status: 'read',
    },
  ],
};
